9.2: Bump bytestring to fix build on i386
The build on i386 was broken due to a bug in bytestring:

    libraries/bytestring/Data/ByteString/Builder/RealFloat/Internal.hs:90:8: error:
        Could not find module ‘GHC.IntWord64’
        Use -v (or `:set -v` in ghci) to see a list of the files searched for.
       |
    90 | import GHC.IntWord64
       |        ^^^^^^^^^^^^^

This should be fixed by
https://github.com/haskell/bytestring/commit/a490fb3f742ea48ab9ed1bc18ce6ad491af6734f.